// Create a `tarpc` service schema
use tarpc::service;

#[service]
pub trait Arithmetic {
	// Just signatures for now.
	async fn add(a: i64, b: i64) -> i64;

	async fn sub(a: i64, b: i64) -> i64;

	async fn mul(a: i64, b: i64) -> i64;

	async fn div(a: i64, b: i64) -> i64;
}

// This is a marker type for a particular implementation of this service.
#[derive(Clone)]
struct ArithmeticService;

// ...And this is its implementation of the service.
impl Arithmetic for ArithmeticService {
	async fn add(self, context: ::tarpc::context::Context, a: i64, b: i64) -> i64 {
		a + b
	}

	async fn sub(self, context: ::tarpc::context::Context, a: i64, b: i64) -> i64 {
		a - b
	}

	async fn mul(self, context: ::tarpc::context::Context, a: i64, b: i64) -> i64 {
		a * b
	}

	async fn div(self, context: ::tarpc::context::Context, a: i64, b: i64) -> i64 {
		a / b
	}
}

// This is where my own code comes in - this macro implements a trait that allows us to
// quickly fork into host and compartment or connect to the service over some kind of
// socket.
use rucompart::compartmentalize;
compartmentalize!(
	// The human-readable name of the service (used later)
	"ARITHMETIC",
	// The path to a type generated by `tarpc`
	ServeArithmetic,
	ArithmeticService,
	// The client stub generated by `tarpc`
	ArithmeticClient,
	// A function that runs upon setup. We don't need to do anything, so it's empty.
	async fn setup(&mut self, mode: rucompart::CompartmentMode) -> Result<_, std::io::Error> {
		println!("Setup!");
		Ok(())
	}
);

// I'll run this in forking mode, for simplicity.
use rucompart::compartment_connect;
use tarpc::context::Context;
use tokio::runtime::Runtime;
fn main() -> eyre::Result<()> {
	let arithmetic_client = compartment_connect!(
		// No address - "connect" by forking.
		None,
		ArithmeticService,
		ArithmeticClient
	);
	// ^ Notice the type inlay - this is a future, but we have to call it *before*
	// starting the runtime, since calling fork with a tokio runtime open is wildly
	// unsafe.
	// Forks, however, are guaranteed never to return out of that macro, so we can
	// proceed knowing that we're the host.
	Runtime::new().unwrap().block_on(async move {
		// Now we can actually run this future to completion.
		let arithmetic_client = arithmetic_client.await;
		let ctx = Context::current();

		// Let's make sure this behaves as we expect...
		assert_eq!(dbg!(arithmetic_client.add(ctx, 2, 2).await?), 4);
		assert_eq!(dbg!(arithmetic_client.sub(ctx, 6, 7).await?), -1);
		assert_eq!(dbg!(arithmetic_client.mul(ctx, 10, 10).await?), 100);
		assert_eq!(dbg!(arithmetic_client.div(ctx, 20, 2).await?), 10);

		Ok(())
	})
}
